os: linux
language: php

cache:
  directories:
    - vendor

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit

after_success:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
